package ch.noseryoung.restaurant.domain.reservation;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Repository
public interface ReservationRepository extends JpaRepository<Reservation, UUID> {

    /* Queries were generated by AI */
    @Query("SELECT r FROM Reservation r JOIN r.tables t WHERE t.id = :tableId AND r.start < :end AND r.end > :start")
    List<Reservation> findOverlappingReservationsForTable(
        @Param("tableId") UUID tableId,
        @Param("start") LocalDateTime start,
        @Param("end") LocalDateTime end
    );

    @Query("SELECT r FROM Reservation r JOIN r.tables t WHERE t.id = :tableId AND r.id != :reservationId AND r.start < :end AND r.end > :start")
    List<Reservation> findOverlappingReservationsExcluding(
        @Param("tableId") UUID tableId,
        @Param("reservationId") UUID reservationId,
        @Param("start") LocalDateTime start,
        @Param("end") LocalDateTime end
    );

    @Query("SELECT r FROM Reservation r WHERE r.start < :end AND r.end > :start")
    List<Reservation> findOverlappingReservations(
        @Param("start") LocalDateTime start,
        @Param("end") LocalDateTime end
    );
}
